name: CI

on: 
  push:
    branches: 
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Copy public to caddy root
      run: mv public/ /root/CV/

